clustername: Play
domain: apps.play.ocp.gp.local

checker:
  schedule: '"0 16 * * 1-4"'
  successfulJobsHistoryLimit: 2
  suspend: false
  updateTime: "05"
  resources:
    limits:
      memory: "500Mi"
      cpu: "500m"
    requests:
      memory: "100Mi"
      cpu: "100m"

updater:
  schedule: '"0 5 * * 2-5"'
  successfulJobsHistoryLimit: 2
  suspend: true
  delay: 1
  resources:
    limits:
      memory: "500Mi"
      cpu: "500m"
    requests:
      memory: "100Mi"
      cpu: "100m"

cleanup:
  schedule: '"0 16 * * 1-4"'
  successfulJobsHistoryLimit: 2
  suspend: false
  delay: 270
  resources:
    limits:
      memory: "500Mi"
      cpu: "500m"
    requests:
      memory: "100Mi"
      cpu: "100m"

slack:
  channel: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDAxRk0zQUNES04vQjAxUTI0NkI1TksvMUFIaHlIUlVsOVlVS2c2WHp5UGh2Z3dDCg==