apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    {{- if .Values.userWorkloadMonitoring.config }}
    {{- toYaml .Values.userWorkloadMonitoring.config | nindent 4 }}
    {{- end }}