applications:
################## RESOURCE LOCKER OPERATOR ###################
  resourceLocker:
    name: resource-locker-operator
    enabled: true
    destination:
      namespace: openshift-operators
      create: false
    argoProject: gepaplexx
    source:
      repoURL: https://github.com/gepaplexx/bundle-openshift
      path: operators/resource-locker/resource-locker-chart
      targetRevision: feature/migrate-to-sealed-secrets
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

################## SEALED SECRETS OPERATOR ####################
  sealedSecretsOperator:
    name: sealed-secrets-operator
    enabled: true
    destination:
      namespace: openshift-gitops
      create: false
    argoProject: gepaplexx
    source:
      chart: sealed-secrets
      repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: 2.*
      helm:
        parameters:
          - name: containerSecurityContext.enabled
            value: 'false'
          - name: podSecurityContext.enabled
            value: 'false'
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

###################### IDENTITY PROVIDER ######################
  identityProvider:
    name: identity-provider
    enabled: false
    destination:
      namespace: gp-infrastructure
      create: true
    argoProject: gepaplexx
    source:
      repoURL: https://github.com/gepaplexx/bundle-openshift
      path: identity-provider/identity-provider-chart
      targetRevision: feature/migrate-to-sealed-secrets
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

####################### CLUSTER-CONFIG ########################
  clusterConfig:
    name: cluster-config
    enabled: true
    destination:
      namespace: gp-infrastructure
      create: true
    argoProject: gepaplexx
    source:
      repoURL: https://github.com/gepaplexx/bundle-openshift
      path: cluster/config/cluster-config-chart
      targetRevision: feature/migrate-to-sealed-secrets
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

####################### CLUSTER-UPDATER #######################
  clusterUpdater:
    name: cluster-updater
    enabled: true
    destination:
      namespace: gp-infrastructure
      create: true
    argoProject: gepaplexx
    source:
      repoURL: https://github.com/gepaplexx/bundle-openshift
      path: cluster/updater/cluster-updater-chart
      targetRevision: feature/migrate-to-sealed-secrets
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

########################### VELERO ############################
  velero:
    name: velero
    enabled: false
    destination:
      namespace: velero
      create: true
    argoProject: gepaplexx
    source:
      repoURL: https://github.com/gepaplexx/bundle-openshift
      path: backup/velero/velero-chart
      targetRevision: feature/migrate-to-sealed-secrets
      helm:
        parameters:
          - name: configuration.backupStorageLocation.bucket
            value: <TODO via ansible vault>
          - name: configuration.backupStorageLocation.config.region
            value: <TODO via ansible vault>
          - name: configuration.backupStorageLocation.config.s3Url
            value: <TODO via ansible vault>
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

########################## ROOK/CEPH ##########################
  rookCeph:
    name: rook-ceph
    enabled: false
    destination:
      namespace: rook-ceph
      create: true
    argoProject: gepaplexx
    source:
      repoURL: https://github.com/gepaplexx/bundle-openshift
      path: storage/rook-ceph/gp-storage-cephcluster-chart
      targetRevision: feature/migrate-to-sealed-secrets
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

################### CLUSTER-LOGGING OPERATOR ##########################
  clusterLoggingOperator:
    name: cluster-logging-operator
    enabled: false
    destination:
      namespace: openshif-logging
      create: true
    argoProject: gepaplexx
    source:
      repoURL: https://github.com/gepaplexx/bundle-openshift
      path: operators/cluster-logging/cluster-logging-operator-chart
      targetRevision: feature/migrate-to-sealed-secrets
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

####################### CLUSTER-LOGGING #######################
  clusterLogging:
    name: cluster-logging
    enabled: false
    destination:
      namespace: openshift-logging
      create: true
    argoProject: gepaplexx
    source:
      repoURL: https://github.com/gepaplexx/bundle-openshift
      path: cluster/logging/cluster-logging-chart
      targetRevision: feature/migrate-to-sealed-secrets
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

##################### CLUSTER-MONITORING ######################
  clusterMonitoring:
    name: cluster-monitoring
    enabled: false
    destination:
      namespace: openshift-monitoring
      create: true
    argoProject: gepaplexx
    source:
      repoURL: https://github.com/gepaplexx/bundle-openshift
      path: cluster/monitoring/cluster-monitoring-chart
      targetRevision: feature/migrate-to-sealed-secrets
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

# TODO certificates/*, registries/*, secret-store/*???,
# TODO Operators: jaeger, oauth-group-sync, pipelines, postgres