apiVersion: v1
kind: Secret
metadata:
  name: github-oauth-secret
  namespace: openshift-config
  annotations:
    avp_path: "secret/data/gp/infrastructure"
type: Opaque
stringData:
  clientSecret: <githubClientSecret>