apiVersion: v1
kind: Secret
metadata:
  name: google-oauth-secret
  namespace: openshift-config
  annotations:
    avp_path: "secret/data/gp/infrastructure"  
type: Opaque
data:
  clientSecret: <googleClientSecret>