{{ if (eq .Values.htpasswd.enable true) }}
apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: patch-identity-prov-htpasswd
  annotations:
    avp_path: {{ .Values.htpasswd.vaultSecretpath }}
spec:
  serviceAccountRef:
    name: resource-locker-sa
  patches:
  - targetObjectRef:
      apiVersion: config.openshift.io/v1
      kind: OAuth
      name: cluster
    patchTemplate: |
      spec:
        identityProviders:
          - name: HTPasswd
            mappingMethod: claim
            type: HTPasswd
            htpasswd:
              fileData: 
                name: <{{ .Values.htpasswd.vaultHtpasswdKey }}>
    patchType: application/strategic-merge-patch+json
    id: patch-identity-prov-htpasswd
{{ end }}