apiVersion: v1
kind: Secret
metadata:
  name: htpass-secret
  namespace: openshift-config
  annotations:
    avp_path: "secret/data/gp/infrastructure"  
type: Opaque  
data:
  htpasswd: <htpasswdUsers>