apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: patch-apiserver
spec:
  serviceAccountRef:
    name: resource-locker-sa
  patches:
    - targetObjectRef:
        apiVersion: config.openshift.io/v1
        kind: APIServer
        name: cluster
      patchTemplate: |
        spec:
          servingCerts:
            namedCertificates:
              - names:
                  - {{ .Values.apiserver.customApiUrl }}
                servingCertificate:
                  name: api-tls
      patchType: application/merge
      id: patch-apiserver