apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-oauth-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgBtX+U/I1XiQIUhWvTpcxNW422DUWRjL6fI+7dQb90D+/60FQ5fh2D53oi6Xnv7NeJVEC7TBNRiWz2knL7CO/yGwST+S25WQgyoYoLTHJ/WpbhEjVcU6rUO2nskCXYLRKrt/QYrSHEg9QG3sKLNLXTmmeCjqwf9BYTkt1E5FBrGlTsWRIlLqdZArgT1Q52UOy0IDCMOi2YJ9AOqWGWltHZ+rUg2fh3+tfsl4avp3BFfxRkUn0Z+CqqF+l4+QMF/B6uppeNdVq2P0TztYfVLb2DRsjBIdktCVxhyt6dE6+u9RJNQS5C9my0CUGlFiT6xE1LaogR3XtWSdW0nNHUnuOD1i9x/+qGv78BDzrUOXX5OmCRZa2nVBIAn7+nVq3lRi8v0ovPIINKR0kW//o1YdqlGhB/MjMGDhio8AmBvXnztdGXLrwQXQUcPnOu2WJqRehTIDK1WscfO/Kg6e1t678e6wUVfddywUhDB9LHLWpxZaVyxNfQW2YdBErgIbdqXN+AiFmaZH37j4ytaeJlA0qq98FneJUJSuc2J2QmNAuf95pLAaGLI3aY1i7xwvJw4tzjY6osAc4iLw/u/3IHP0+oTDPwzCeITEmD9s2CYhg1SeERGhZzdeEi8vwrL0EL14q8WMtAiriYD0CK0xYs01pmraq5epBpm61k13SgRGMpfXTCD4zXyLjXcth9+RHZdow8ODj+oeI0gtwpONrJN2SsL/GfPdZLSxL6lG6fScT8nNcz9D1CP33MJ
  template:
    metadata:
      creationTimestamp: null
      name: github-oauth-secret
      namespace: openshift-config

