apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: google-oauth-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgAxl6lH4+nJsOhmpd1wr6nATh8W4pcMy51UclKVpYiA3p09u3eVjOV+eMlH3Wx6MKsDDRvc18MmK5aKPTrcaHP1Ozko6+5oYEBCvATKaWS1mPxiSVGkSE5/eAan6f7xG+C078fSyi3hvR/SNewVi5AdW/+LjR92SvRInTZKp9m1pBPT29z5JD2NtK10L3xJ8KO5UtLU1bqAQNWR1+x3DQnsm0yjmERwggAO/bMBMN/6ssC8SYAXFK+8b7mginkHnNWHMK516QtVy9vsoFwVWJm0wc2npetyBAR04an9waiS3PrHV7sJsWWaQLWlpzxwDXg+WnFup9OX2DzuMjBAFCmXLlt3kYos0WWKHBPI2JNBzGyCWc3e4xsN3BmYwGHLD5iDzFVVhiRyzA4Fjz/9cStUVkVedX/YOeQmwsuFy53xz0kSWrPepdwHV0275V5u/uQ6apAdFzJhBUhsxoSmgsW8AnWpD/lUN9S8Sf62ooMri+/KCCGuEtNc5FxRUdkRyn5cnHyGRitsDbFpqZmYodnAZj5/+aap3/XWMhjuLE+KU8SKDrVrf9XoderWabk4bcmjL26kUHdQ6mHBdC4tMix5zS1MVUkxg8gZjpE4G10X8pOfyZLazyf+IY2qKpc4Q33O/Xm8xnH0FPyK1fVb00CyTAgIL5RCKtXGIkNNHopmYKI3jGIpNSY3BeqOjvdVCvbRTB2iAlViBqd4hDlD0fxsEOZLze/Ru6k=
  template:
    metadata:
      creationTimestamp: null
      name: google-oauth-secret
      namespace: openshift-config

