apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpass-oauth-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: {{ .Values.htpasswd.data }}
  template:
    metadata:
      creationTimestamp: null
      name: htpass-oauth-secret
      namespace: openshift-config

