clusterlogging:
  managementState: "Managed"

elasticsearch:
  retentionPolicy: 
    application:
      maxAge: 30d
    infra:
      maxAge: 30d
    audit:
      maxAge: 2d
  resources:
    limits:
      memory: "4Gi"
      cpu: "1"
    requests:
      cpu: "500m"
      memory: "2Gi"
  nodeCount: 3       
  storage:
    storageClassName: rook-ceph-fs
    size: 30G
  redundancyPolicy: "SingleRedundancy"

kibana:
  replicas: 1

curator:
  schedule: "30 * * * *"