{{- if and .Values.credentials.useSecret .Values.credentials.useSealedSecret (not .Values.credentials.existingSecret) -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "velero.secretName" . }}
spec:
  encryptedData:
    cloud: {{ .Values.credentials.sealedSecretContent }}
  template:
    metadata:
      name: {{ include "velero.secretName" . }}
    type: Opaque
{{- end }}
