{{ if (eq .Values.git.enable true) }}
apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: patch-identity-prov-git
spec:
  serviceAccountRef:
    name: resource-locker-sa
  patches:
  - targetObjectRef:
      apiVersion: config.openshift.io/v1
      kind: OAuth
      name: cluster
    patchTemplate: |
      spec:
        identityProviders:
          - name: Gepaplexx
            mappingMethod: claim
            type: GitHub
            github:
              clientID: {{ .Values.git.clientId }}
              clientSecret:
                name: {{ .Values.git.k8secretName }}
              organizations: [{{ .Values.git.restrOrgs }}]
    patchType: application/strategic-merge-patch+json
    id: patch-identity-prov-git
{{ end }}