{{ if (eq .Values.google.enable true) }}
apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: patch-identity-prov-google
spec:
  serviceAccountRef:
    name: resource-locker-sa
  patches:
  - targetObjectRef:
      apiVersion: config.openshift.io/v1
      kind: OAuth
      name: cluster
    patchTemplate: |
      spec:
        identityProviders:
          - name: Gepardec
            mappingMethod: claim
            type: Google
            google:
              clientID: {{ .Values.google.clientId }}
              clientSecret:
                name: {{ .Values.google.k8secretName }}
              hostedDomain: {{ .Values.google.restrDomain }}
    patchType: application/merge-patch+json
    id: patch-identity-prov-google
{{ end }}