{{- if (eq .Values.identityProvider.enabled true)}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: identity-provider
spec:
  destination:
    namespace: {{ default .Release.Namespace .Values.identityProvider.destination.namespace }}
    server: 'https://kubernetes.default.svc'
  project: {{ default "default" .Values.identityProvider.argoProject }}
  source:
    path: {{ .Values.identityProvider.source.path }}
    repoURL: {{ .Values.identityProvider.source.repoURL }}
    targetRevision: {{ .Values.identityProvider.source.targetRevision }}
syncPolicy:
  automated:
    prune: {{ .Values.identityProvider.syncPolicy.automated.prune }}
    selfHeal: {{ .Values.identityProvider.syncPolicy.automated.selfHeal }}
  syncOptions:
    - CreateNamespace={{ .Values.identityProvider.destination.create }}
{{- end }}
