apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-tls
  namespace: openshift-config
spec:
  secretName: api-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - {{ .Values.certificates.api }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer