apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-tls
  namespace: openshift-ingress
spec:
  secretName: default-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - {{ .Values.certificates.defaultIngress | quote }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer