{{ if (eq .Values.htpasswd.enable true) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.htpasswd.k8secretName }}
  namespace: openshift-config
type: Opaque  
stringData:
  htpasswd: {{ .Values.htpasswd.data }}
{{ end }}