---
name: Build and push Helm charts

'on':
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

jobs:
  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: |
            helm lint ./bke/*/.


  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Openshift GitOps Operator Helm Chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.PAT }}
          charts_dir: ./operators/openshift-gitops
          charts_url: https://gepaplexx.github.io/gp-helm-charts/
          owner: gepaplexx
          repository: gp-helm-charts
          branch: main

      - name: Publish Identity Provider Helm Charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.PAT }}
          charts_dir: ./identity-provider
          charts_url: https://gepaplexx.github.io/gp-helm-charts/
          owner: gepaplexx
          repository: gp-helm-charts
          branch: main
